#!/usr/bin/env python3
"""
fix_mavlink_headers.py

Two fixes applied together before building ArduPlane/ArduCopter:

Fix 1 — Remove spurious pre-generated MAVLink headers from the source tree.
  Cause: libraries/GCS_MAVLink/include/ is not tracked by git but may exist
  from a manual `mavgen.py` run.  The waf build compiles from build/<board>/
  and resolves `-Ilibraries/GCS_MAVLink` relative to that directory, so it
  always uses build/<board>/libraries/GCS_MAVLink/include/ (generated by waf's
  own mavgen step).  The source-tree copy is therefore never used by waf, but
  its presence can cause confusion and stale-header bugs if a developer also
  adds it to an IDE's include path.  Safe to remove at any time; waf will
  regenerate the correct headers into the build directory on the next build.

Fix 2 — Ensure TRACKING_MESSAGE is present in the mavlink submodule.
  TRACKING_MESSAGE (ID 11045) is committed in modules/mavlink at commit
  1430834b ("ardupilotmega: add TRACKING_MESSAGE (id 11045)").  When the
  submodule is correctly initialised this fix is a no-op.  If the submodule
  was reset to upstream, or the repo was cloned without --recurse-submodules,
  the fix first tries `git submodule update` (which checks out 1430834b) and
  falls back to applying fix_mavlink_tracking_message.patch directly.

Usage:
  python3 fix_mavlink_headers.py           # apply all fixes
  python3 fix_mavlink_headers.py --check   # check status only, no changes
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Commit in modules/mavlink that contains TRACKING_MESSAGE
TRACKING_COMMIT = "1430834b"


def fix_spurious_headers(check_only: bool) -> bool:
    stale = ROOT / "libraries" / "GCS_MAVLink" / "include"
    if stale.is_dir():
        if check_only:
            print(f"[CHECK] WARN — spurious source-tree headers exist: {stale}")
            print("         These are not used by waf (which uses build/<board>/libraries/...")
            print("         Run without --check to remove them.")
            return False
        print(f"[fix 1] Removing spurious source-tree headers: {stale}")
        shutil.rmtree(stale)
        print("[fix 1] Done.")
    else:
        print("[fix 1] OK — no spurious source-tree headers found.")
    return True


def fix_tracking_message(check_only: bool) -> bool:
    ardupilotmega = (
        ROOT / "modules" / "mavlink" / "message_definitions" / "v1.0" / "ardupilotmega.xml"
    )
    patch_file = ROOT / "fix_mavlink_tracking_message.patch"

    # Already present — nothing to do
    if ardupilotmega.is_file() and "TRACKING_MESSAGE" in ardupilotmega.read_text():
        print("[fix 2] OK — TRACKING_MESSAGE already present in ardupilotmega.xml.")
        return True

    if check_only:
        result = subprocess.run(
            ["git", "submodule", "status", "modules/mavlink"],
            cwd=ROOT, capture_output=True, text=True,
        )
        print("[CHECK] FAIL — TRACKING_MESSAGE missing from ardupilotmega.xml.")
        print(f"         submodule status : {result.stdout.strip()}")
        print(f"         expected commit  : {TRACKING_COMMIT}")
        print("         Run without --check to fix (git submodule update).")
        return False

    # Primary: git submodule update (checks out commit 1430834b with TRACKING_MESSAGE)
    print("[fix 2] Running: git submodule update --init modules/mavlink ...")
    result = subprocess.run(
        ["git", "submodule", "update", "--init", "modules/mavlink"],
        cwd=ROOT,
    )
    if result.returncode == 0:
        if ardupilotmega.is_file() and "TRACKING_MESSAGE" in ardupilotmega.read_text():
            print("[fix 2] Done via submodule update.")
            return True
        print("[fix 2] Submodule updated but TRACKING_MESSAGE still missing "
              "— falling back to patch.")

    # Fallback: apply the patch directly (e.g. submodule remote unreachable)
    if not patch_file.is_file():
        print(f"[fix 2] ERROR — patch file not found: {patch_file}", file=sys.stderr)
        return False

    print(f"[fix 2] Applying {patch_file.name} to modules/mavlink ...")
    result = subprocess.run(
        ["git", "apply", str(patch_file)],
        cwd=ROOT / "modules" / "mavlink",
    )
    if result.returncode != 0:
        print("[fix 2] ERROR — git apply failed.", file=sys.stderr)
        return False
    print("[fix 2] Done via patch fallback.")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--check", action="store_true",
                        help="Check status only, make no changes")
    args = parser.parse_args()

    ok1 = fix_spurious_headers(args.check)
    ok2 = fix_tracking_message(args.check)

    if not args.check:
        print("\nAll fixes applied. Next steps:")
        print("  ./waf configure --board <board>")
        print("  ./waf plane      # ArduPlane")
        print("  ./waf copter     # ArduCopter")

    return 0 if (ok1 and ok2) else 1


if __name__ == "__main__":
    sys.exit(main())
